#!/home/client/Documents/fun/py/venv/bin/python3
import numpy as np

"""
архитектура модели MLP (с backpropogation)
Версия 2
"""


class Linear:
  def __init__(self, in_features, out_features):
    self.W = np.random.randn(in_features, out_features) * 0.1
    self.b = np.zeros(out_features)
    self.X = []
        
  def forward(self, X):
    self.X = X
    return X @ self.W + self.b

  def backward(self, grad_output):
    # grad_output = dL/dY
    X = self.X
    # dL/dW
    grad_W = X.T @ grad_output
    # dL/db
    grad_b = grad_output.sum(axis=0)
    # dL/dX
    grad_X = grad_output @ self.W.T
 
    return grad_X, grad_W, grad_b


class ReLU:
  def forward(self, X):
    return np.maximum(X, 0)

  def backward(self, grad_output, X):
    # dL/dX = dL/dY * dY/dX
    grad_X = grad_output * (X > 0)

    return grad_X


class SGD:
  def __init__(self, params, lr):
    self.params = params
    self.lr = lr

  def step(self):
    if self.params == ():
      return
      
    print(f'params = \n{params}')
      
    exit(0)  
    w1, grad_w1, b1, grad_b1, w2, grad_w2, b2, grad_b2 = self.params
    
    w1 -= self.lr * grad_w1
    b1 -= self.lr * grad_b1
    w2 -= self.lr * grad_w2
    b2 -= self.lr * grad_b2

class MLP:
  def __init__(self):
    self.fc1 = Linear(2, 4)
    self.relu = ReLU()
    self.fc2 = Linear(4, 1)
 
    # cache grads
    self.grad_W1 = np.array([])
    self.grad_b1 = np.array([])
    self.grad_W2 = np.array([])
    self.grad_b2 = np.array([])
  
  def forward(self, X):
    self.z1 = self.fc1.forward(X)
    self.a1 = self.relu.forward(self.z1)
    self.y = self.fc2.forward(self.a1)

    return self.y

  def backward(self, grad_loss, X):
    grad_a1, grad_W2, grad_b2 = self.fc2.backward(grad_loss)
    grad_z1 = self.relu.backward(grad_a1, self.z1)
    _, grad_W1, grad_b1 = self.fc1.backward(grad_z1)
  
    self.grad_W1 = grad_W1
    self.grad_b1 = grad_b1
    self.grad_W2 = grad_W2
    self.grad_b2 = grad_b2
    
    self.parameters((self.fc1.W, self.grad_W1, 
                     self.fc1.b, self.grad_b1, 
                     self.fc2.W, self.grad_W2, 
                     self.fc2.b, self.grad_b2))
    return grad_W1, grad_b1, grad_W2, grad_b2

  def parameters(self, grads=()):
    return grads

def main():

  X = np.array([
    [2., 3.],
    [1., 4.],
    [3., 1.],
    [5., 2.]
  ])

  target = np.array([
    [10.],
    [9.],
    [7.],
    [13.]
  ])

  model = MLP()
  optim = SGD(model.parameters(), lr=0.01)

  for step in range(1000):
    pred = model.forward(X)
    loss = ((pred - target) ** 2).mean()
    grad_loss = 2 * (pred - target) / len(X)
    grads = model.backward(grad_loss, X)
 
    optim.step()
    print("asdasdsad")

    if step % 100 == 0:
      print(f"step={step}, loss={loss:.6f}")



if __name__ == "__main__":
    main()
